config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'

  get '/hello', to: 'application#hello'

  resources :doctors

  # get '/doctors', to: 'doctors#index'
  # get '/doctors/:id', to: 'doctors#show', as: 'doctor'

  root 'doctors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital

  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    @hello = "hello there!"
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
  end

  def edit
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @welcome = "Welcome to the website"
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/hello.html.erb
<h1>Hello Page</h1>

<%= @hello %>

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<p>Find me in app/views/doctors/edit.html.erb</p>

app/views/doctors/index.html.erb
<% provide(:title, "All Doctors") %>
<h1>All Doctors</h1>

<ul>
  <% @doctors.each do |doctor| %>
    <li><%= link_to doctor.name, doctor_path(doctor) %></li>
  <% end %>
</ul>

<hr>

<h4>More coming soon</h4>

app/views/doctors/new.html.erb
<h1>Doctors#new</h1>
<p>Find me in app/views/doctors/new.html.erb</p>

app/views/doctors/show.html.erb
<% provide(:title, "Doctor Details") %>
<h1>Doctors Details</h1>

<p>Name: <%= @doctor.name %></p>
<p>Experience: <%= @doctor.experience %></p>
<p>Home Hospital: <%= @doctor.hospital.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1><%= @welcome %></h1>
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>